Create product list component and UI
Snow-Penguins/cacart pull request #10
Opened 2024-03-31 20:09 UTC by Euna-kim-1

**Jira Ticket**<br>
Link: https://derek-team-lva74agprdbm.atlassian.net/browse/SP-77

**Description**<br>
_Add a sensible description to this pull request:_

- Added: `components/productCard.tsx`, `components/productCardList.tsx`, `public/images/product1.jpg`, `public/images/product2.jpg`, `public/images/product3.jpg`, `styles/productCard.module.css`
- Changed: `app/(home)/page.tsx`

**Screenshots**<br>
<img width="1445" alt="스크린샷 2024-03-31 오후 1 53 43" src="https://github.com/Snow-Penguins/cacart/assets/122576435/843d1918-c546-4e4a-a6ec-750a6153220a">

2024-03-31 20:45 UTC, derekhskim commented
We need to run prettier fix script set on package.json. Please run npm run prettier-fix and push your edited changes to allow checks to pass! :)

2024-04-01 02:06 UTC, jay-kj-woo requested changes

2024-04-01 02:06 UTC, jay-kj-woo commented on components/productCardList.tsx
> +interface Product {
`Product` interface is repeating in here. Could we export it from the Product.tsx file for better maintainability? 
This is not necessary now and more of a heads-up, but it is good think about the nature of Product entity and where we gets this data from. Once we establish api endpoints, we would likely create a type/interface for the api responses, and would use that here directly or indirectly.

2024-04-01 02:06 UTC, jay-kj-woo commented on components/productCard.tsx
> +  const productImages = [
[Not a blocker] As this array serves as a constant data piece, we could perhaps name it as `PRODUCT_IMAGES` following the capital letter snake case and place it outside the component function to clearly show that is does not relate to the component code logic?

2024-04-05 02:23 UTC, jay-kj-woo approved these changes

2024-04-05 05:12 UTC, merged